import { z } from 'zod';

export const createGuestSchema = z.object({
  body: z.object({
    firstName: z.string().min(1, 'Nome é obrigatório').max(255, 'Nome deve ter no máximo 255 caracteres'),
    lastName: z.string().min(1, 'Sobrenome é obrigatório').max(255, 'Sobrenome deve ter no máximo 255 caracteres'),
    email: z.string().email('E-mail inválido').optional().nullable(),
    phone: z.string().max(20, 'Telefone deve ter no máximo 20 caracteres').optional().nullable(),
    documentType: z.enum(['cpf', 'passport', 'rg', 'cnh', 'cnpj', 'other']).optional().nullable(),
    documentNumber: z.string().max(50, 'Número do documento deve ter no máximo 50 caracteres').optional().nullable(),
    nationality: z.string().max(100, 'Nacionalidade deve ter no máximo 100 caracteres').optional().nullable(),
    birthDate: z.string().date('Data de nascimento inválida').optional().nullable(),
    gender: z.enum(['male', 'female', 'other', 'prefer_not_to_say']).optional().nullable(),
    address: z.string().max(500, 'Endereço deve ter no máximo 500 caracteres').optional().nullable(),
    city: z.string().max(100, 'Cidade deve ter no máximo 100 caracteres').optional().nullable(),
    state: z.string().max(50, 'Estado deve ter no máximo 50 caracteres').optional().nullable(),
    zipCode: z.string().max(20, 'CEP deve ter no máximo 20 caracteres').optional().nullable(),
    country: z.string().max(100, 'País deve ter no máximo 100 caracteres').optional().nullable(),
    tier: z.enum(['bronze', 'silver', 'gold', 'platinum']).optional().default('bronze'),
    loyaltyPoints: z.number().int().min(0).optional().default(0),
    preferences: z.array(z.string()).optional().nullable(),
    tags: z.array(z.string()).optional().nullable(),
    notes: z.string().optional().nullable(),
    marketingConsent: z.boolean().optional().default(false),
    type: z.enum(['physical', 'legal']).optional().default('physical'),
    whatsapp: z.string().max(20).optional().nullable(),
    companyName: z.string().max(255).optional().nullable(),
    tradeName: z.string().max(255).optional().nullable(),
    stateRegistration: z.string().max(50).optional().nullable(),
    cnpj: z.string().max(20).optional().nullable(),
    contactName: z.string().max(255).optional().nullable(),
    addressNumber: z.string().max(20).optional().nullable(),
    addressComplement: z.string().max(100).optional().nullable(),
    addressNeighborhood: z.string().max(100).optional().nullable(),
    memberSince: z.string().date().optional().nullable(),
    marketingEmail: z.boolean().optional().default(true),
    marketingSms: z.boolean().optional().default(true),
    marketingWhatsapp: z.boolean().optional().default(true),
    emergencyContactName: z.string().max(255).optional().nullable(),
    emergencyContactPhone: z.string().max(20).optional().nullable(),
    emergencyContactRelation: z.string().max(50).optional().nullable(),
    occupation: z.string().max(100).optional().nullable(),
    avatar: z.string().max(500).optional().nullable(),
    password: z.string().min(6, 'Senha deve ter no mínimo 6 caracteres').max(255).optional().nullable(),
  }),
});

export const updateGuestSchema = z.object({
  body: z.object({
    firstName: z.string().min(1).max(255).optional(),
    lastName: z.string().min(1).max(255).optional(),
    email: z.string().email().optional().nullable(),
    phone: z.string().max(20).optional().nullable(),
    documentType: z.enum(['cpf', 'passport', 'rg', 'cnh', 'cnpj', 'other']).optional().nullable(), // Added cnpj
    documentNumber: z.string().max(50).optional().nullable(),
    nationality: z.string().max(100).optional().nullable(),
    birthDate: z.string().date().optional().nullable(),
    gender: z.enum(['male', 'female', 'other', 'prefer_not_to_say']).optional().nullable(),
    address: z.string().max(500).optional().nullable(),
    city: z.string().max(100).optional().nullable(),
    state: z.string().max(50).optional().nullable(),
    zipCode: z.string().max(20).optional().nullable(),
    country: z.string().max(100).optional().nullable(),
    tier: z.enum(['bronze', 'silver', 'gold', 'platinum']).optional(),
    loyaltyPoints: z.number().int().min(0).optional(),
    preferences: z.array(z.string()).optional().nullable(),
    tags: z.array(z.string()).optional().nullable(),
    notes: z.string().optional().nullable(),
    marketingConsent: z.boolean().optional(),
    type: z.enum(['physical', 'legal']).optional(),
    whatsapp: z.string().max(20).optional().nullable(),
    companyName: z.string().max(255).optional().nullable(),
    tradeName: z.string().max(255).optional().nullable(),
    stateRegistration: z.string().max(50).optional().nullable(),
    cnpj: z.string().max(20).optional().nullable(),
    contactName: z.string().max(255).optional().nullable(),
    addressNumber: z.string().max(20).optional().nullable(),
    addressComplement: z.string().max(100).optional().nullable(),
    addressNeighborhood: z.string().max(100).optional().nullable(),
    memberSince: z.string().date().optional().nullable(),
    marketingEmail: z.boolean().optional(),
    marketingSms: z.boolean().optional(),
    marketingWhatsapp: z.boolean().optional(),
    emergencyContactName: z.string().max(255).optional().nullable(),
    emergencyContactPhone: z.string().max(20).optional().nullable(),
    emergencyContactRelation: z.string().max(50).optional().nullable(),
    occupation: z.string().max(100).optional().nullable(),
    avatar: z.string().max(500).optional().nullable(),
    password: z.string().min(6).max(255).optional().nullable(),
  }),
});

export const addLoyaltyPointsSchema = z.object({
  body: z.object({
    operation: z.enum(['credit', 'debit'], { required_error: 'Operação é obrigatória (credit ou debit)' }),
    points: z.number().int().min(1, 'Quantidade deve ser pelo menos 1'),
    source: z.string().max(80).optional().default('manual'),
    description: z.string().max(500).optional().nullable(),
  }),
});

export type CreateGuestInput = z.infer<typeof createGuestSchema>['body'];
export type UpdateGuestInput = z.infer<typeof updateGuestSchema>['body'];
export type AddLoyaltyPointsInput = z.infer<typeof addLoyaltyPointsSchema>['body'];
